services:
  db:
    image: postgres
    container_name: nature-trip-m3
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nature-trip-m3
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: